# 2025-26 Project

##### Import libraries

In [1]:
import pandas as pd
import numpy as np

### 1. Create a single dataframe with the concatenation of all input csv files, adding a column called country

In [2]:
CA = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\CAvideos.csv')
DE = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\DEvideos.csv')
FR = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\FRvideos.csv')
GB = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\GBvideos.csv')
IN = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\INvideos.csv')
JP = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\JPvideos.csv', encoding_errors = 'replace')
KR = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\KRvideos.csv', encoding_errors = 'replace')
MX = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\MXvideos.csv', encoding_errors = 'replace')
RU = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\RUvideos.csv', encoding_errors = 'replace')
US = pd.read_csv('C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\USvideos.csv')

In [3]:
CA['Country'] = 'CA'
DE['Country'] = 'DE'
FR['Country'] = 'FR'
GB['Country'] = 'GB'
IN['Country'] = 'IN'
JP['Country'] = 'JP'
KR['Country'] = 'KR'
MX['Country'] = 'MX'
RU['Country'] = 'RU'
US['Country'] = 'US'

In [4]:
list_country = [CA, DE, FR, GB, IN, JP, KR, MX, RU, US]
df = pd.concat(list_country)
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
40947,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

In [5]:
df.reset_index(inplace = True)
index = []
for i in range(len(df)):
    index.append(i)
df['index'] = index

In [6]:
df.set_index('index', inplace = True)
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country
index,,,,,,,,,,,,,,,,,
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US

### 2. Extract all videos that have no tag.

In [7]:
df[df['tags'] == '[none]'][['video_id', 'title', 'description']]

,video_id,title,description
index,,,
41,JwboxqDylgg,Canada Soccer's Women's National Team v USA In...,Canada Soccer's Women's National Team face riv...
58,9B-q8h31Bpk,John Oliver Tackles Louis C.K. And Donald Trum...,"John Oliver on News, Politics ..."
78,1UE5Dq1rvUA,Taylor Swift Perform Ready For It - SNL,Thanks for watching please subscribe and subsc...
86,pmJQ4KwliX4,"LATEST Q POSTS: ROTHSCHILDS, HOUSE OF SAUD, lL...",https://pastebin.ca/3930472\n\nSupport My Chan...
98,lHcXhBojpeQ,三屆TVB視帝，拋棄10年青梅竹馬髮妻，為娶小三還不惜與母絕交！,NaN
...,...,...,...
375815,VGykknw9eCM,"Made Defiant: The Mixtape ft. Neymar Jr., Kane...","When your time comes, you have two choices. Yo..."
375819,fAIX12F6958,Bumblebee (2018) - Official Teaser Trailer - P...,Every adventure has a beginning. Watch the off...
375865,gS1DbvHHVH0,Going in to brain surgery,We’ll post an update on Instagram and Twitter ...
375873,E4c7EE8_IX0,Weezer - Africa,Stream + download the song: http://fanlink.to/...
375938,1h7KV2sjUWY,True Facts : Ant Mutualism,NaN

### 3. For each channel, determine the total number of views

Since there are several videos that have trended multiple times and in different countries, the logic was to keep only the row with the last 'trending_date', eliminating any duplicates.
The total number of views is an objective metric, so the view counts from different countries but taken in the same day are equal.

However there are some problems: there are some videos with no video_id, instead there is '#NAME?' or '#VALUE!' in the column video_id. so in the parameter subset of the function drop_duplicates, that tels on which columns controll the possible duplicates, I select 'video_id', 'channel_title' and 'publish_time'.

In [8]:
df.sort_values(['video_id', 'trending_date']).drop_duplicates(subset = ['video_id', 'publish_time', 'channel_title'], keep = 'last').groupby('channel_title').sum()[['views']]

                          views
channel_title
! 세상에 무슨일이              1052789
!!8時だよ面白ネタ大集合             50207
!BTS・TWICE まとめ             7310
!Los amorosos Virales¡     6069
!t Live                  194690
...                         ...
５分でできる DIY               183245
ＢＡＳＨｔｖ                   116292
Ｋのフィッシングちゃんねる             37165
ＷＡＪＯＩＫＡ                  424129
💜Sandrea                 188204

[37824 rows x 1 columns]

### 4. Save all rows with disabled comments and disabled ratings, or that have video_error_or_removed in a new dataframe called excluded, and remove those rows from the original dataframe.

In [9]:
excluded = df[((df['comments_disabled'] == True) & (df['ratings_disabled'] == True)) | (df['video_error_or_removed'] == True)]
excluded

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country
index,,,,,,,,,,,,,,,,,
173,H8IWLEtFt9A,17.14.11,Intégrale - On n'est pas couché 11 novembre 20...,On n'est pas couché,24,2017-11-12T01:44:07.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",122282,0,0,0,https://i.ytimg.com/vi/H8IWLEtFt9A/default.jpg,True,True,False,Intégrale - On n'est pas couché 11 novembre 20...,CA
1069,om-_yJaSW_Y,17.19.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",523258,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1278,om-_yJaSW_Y,17.20.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1004809,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
1320,faJOpxEyTWk,17.20.11,Intégrale - On n'est pas couché 18 novembre 20...,On n'est pas couché,24,2017-11-19T02:01:15.000Z,"onpc|""on n'est pas couche""|""laurent ruquier""|""...",87544,0,0,0,https://i.ytimg.com/vi/faJOpxEyTWk/default.jpg,True,True,False,Intégrale - On n'est pas couché 18 novembre 20...,CA
1573,om-_yJaSW_Y,17.21.11,GET READY WITH US Feat: JACLYN HILL & MANNY MUA,Laura Lee,26,2017-11-18T19:24:49.000Z,"Laura88Lee|""grwm""|""chit chat get ready with me...",1197269,0,0,0,https://i.ytimg.com/vi/om-_yJaSW_Y/default.jpg,True,True,False,"Hey Larlees, todays video is a get ready with ...",CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368180,1Aoc-cd9eYs,18.07.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",672609,4916,197,1269,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368407,1Aoc-cd9eYs,18.08.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",412323,25441,208,952,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368613,1Aoc-cd9eYs,18.09.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",251857,6623,231,1120,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
368830,1Aoc-cd9eYs,18.10.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",629055,30695,277,1033,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US
369587,1Aoc-cd9eYs,18.14.05,Cobra Kai Ep 2 - Strike First - The Karate Kid...,Cobra Kai,24,2018-05-02T16:02:35.000Z,"Cobra Kai|""Karate Kid""|""YouTube Red Original S...",1062499,32276,4594,5547,https://i.ytimg.com/vi/1Aoc-cd9eYs/default.jpg,False,False,True,Present day Daniel LaRusso lives a charmed lif...,US

In [10]:
df_new = df.drop(excluded.index)

In [11]:
# check if the number of rows deleted from the original df are the same of the number of rows of 'excluded'
df_new.shape[0] + excluded.shape[0] == df.shape[0]

True

### 5. Add a like_ratio column storing the ratio between the number of likes and of dislikes

Using np.where to calculate 'like_ratio' conditionally:
- Compute likes / dislikes only when both likes and dislikes are greater than 0.
- If either is 0, assign None to avoid division by zero or meaningless ratios.

In [12]:
df_new['like_ratio'] = np.where(
    (df_new['likes'] > 0) & (df_new['dislikes'] > 0),
    df_new['likes'] / df_new['dislikes'],
    None
)
df_new[df_new['like_ratio'].isnull()]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country,like_ratio
index,,,,,,,,,,,,,,,,,,
67,amEZKmJQ4Io,17.14.11,Drako - Watch Me Do It [Official Video],babygranderecords,10,2017-10-23T19:38:36.000Z,"Drako|""Watch Me Do It""|""watch me""|""migos""|""dap...",25887,0,0,6,https://i.ytimg.com/vi/amEZKmJQ4Io/default.jpg,False,True,False,PURCHASE / STREAM WATCH ME DO IT https://fanli...,CA,None
161,bsgocWaULIU,17.14.11,Troydon bent - Jam African,Troydon bent,10,2016-12-08T19:29:25.000Z,New Danchall music world reggae traditional so...,16921,187,0,5,https://i.ytimg.com/vi/bsgocWaULIU/default.jpg,False,False,False,Troydon bent performing Jam African produced b...,CA,None
235,wDEA3rpYHnI,17.15.11,Marie-Louise Arsenault réplique à Denise Bomba...,TV Classics,22,2017-11-13T01:26:37.000Z,Marie-Louise Arsenault qui réplique à Denise B...,15800,88,0,0,https://i.ytimg.com/vi/wDEA3rpYHnI/default.jpg,True,False,False,Moment favori à la télé québécoise: Marie-Loui...,CA,None
271,LfajgipdxmA,17.15.11,How does Yoonla work? Learning CPA,Anthonys Digital Lifestyle Dotcom,22,2017-11-14T10:57:38.000Z,"How does Yoonla work|""free work from home""|""le...",11810,1,0,0,https://i.ytimg.com/vi/LfajgipdxmA/default.jpg,False,False,False,How does Yoonla work? Learning CPA marketing t...,CA,None
313,8sdQ7dP9Drs,17.15.11,"Today's News: It's On - Get The Goods, Novembe...",Whistler Blackcomb,17,2017-11-14T18:18:21.000Z,[none],4851,31,0,0,https://i.ytimg.com/vi/8sdQ7dP9Drs/default.jpg,False,False,False,Today’s news: it’s on. Whistler Mountain will ...,CA,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358439,8WbxbqwdWog,18.13.03,Camera Goes on Japanese Sushi Conveyor Belt Sh...,TkyoSam,22,2018-03-06T16:18:30.000Z,"東京サム|""jvlog""|""jvlogger""|""tkyosam""|""tokyo""|""sam...",639517,0,0,1059,https://i.ytimg.com/vi/8WbxbqwdWog/default.jpg,False,True,False,I will call this video A Camera's Journey Thro...,US,None
360544,zkrq7Kpd1so,18.24.03,ULTRA LIVE presents Ultra Music Festival 2018 ...,UMF TV,10,2018-03-24T07:55:21.000Z,"ultra music festival|""umf""|""mix""|""relive""|""aft...",1648886,0,0,548,https://i.ytimg.com/vi/zkrq7Kpd1so/default.jpg,False,True,False,Tune in here for the Ultra Music Festival 2018...,US,None
363543,9TUBf6l7FBg,18.14.04,Coachella 2018 LIVE Channel 1,Coachella,10,2018-04-05T06:48:28.000Z,[none],3598220,0,0,0,https://i.ytimg.com/vi/9TUBf6l7FBg/default_liv...,False,True,False,For more cameras and VR180 immersive experienc...,US,None
363744,9TUBf6l7FBg,18.15.04,Coachella 2018 LIVE Channel 1,Coachella,10,2018-04-05T06:48:28.000Z,[none],11137071,0,0,2,https://i.ytimg.com/vi/9TUBf6l7FBg/default_liv...,False,True,False,For more cameras and VR180 immersive experienc...,US,None
363948,9TUBf6l7FBg,18.16.04,Coachella 2018 LIVE Channel 1,Coachella,10,2018-04-05T06:48:28.000Z,[none],24004779,0,0,3,https://i.ytimg.com/vi/9TUBf6l7FBg/default_liv...,False,True,False,For more cameras and VR180 immersive experienc...,US,None

### 6. Cluster the publish time into 10-minute intervals (e.g. from 02:20 to 02:30)

In [13]:
df_new['publish_time'] = pd.to_datetime(df_new['publish_time'])
df_new['publish_time'].dtypes

datetime64[ns, UTC]

In [14]:
# floor the time to nearest 10-minutes starting point (round down)
start_times = df_new['publish_time'].dt.floor('10min')
end_times = start_times + pd.Timedelta(minutes=10)

# extract only hour and minutes for labels
df_new['cluster_hour'] = (
    "from " + start_times.dt.strftime('%H:%M') + 
    " to " + end_times.dt.strftime('%H:%M')
)

### 7. For each interval, determine the number of videos, average number of likes and of dislikes.

The logic is the same of 3° point, keeping only the last 'trending_date' and deleting others.

In [15]:
df_unique = df_new.sort_values(['video_id', 'trending_date']).drop_duplicates(
    subset=['video_id', 'publish_time', 'channel_title'], 
    keep='last'
).copy()

In [16]:
# group by created clusters and aggregate metrics
df_unique.groupby('cluster_hour').agg(
    n_videos=('video_id', 'count'),
    avg_likes=('likes', 'mean'),
    avg_dislikes=('dislikes', 'mean')
).round(2)

                     n_videos  avg_likes  avg_dislikes
cluster_hour
from 00:00 to 00:10      1391   11022.87        937.30
from 00:10 to 00:20       752    7148.66        415.57
from 00:20 to 00:30       658    7765.37        638.77
from 00:30 to 00:40       845    7189.55        316.15
from 00:40 to 00:50       641    8119.08        458.18
...                       ...        ...           ...
from 23:10 to 23:20       808    7461.24        465.49
from 23:20 to 23:30       723    9726.39        608.48
from 23:30 to 23:40       909    6541.64        406.01
from 23:40 to 23:50       743    9306.83       1086.10
from 23:50 to 00:00       694    5505.65        379.63

[144 rows x 3 columns]

### 8. For each tag, determine the number of videos

First of all, it is important to clean tags.

In [17]:
df_new['tags']=df_new['tags'].str.replace('"','')
df_new['tags']=df_new['tags'].str.replace('#','')
df_new['tags']=df_new['tags'].str.replace('/','|')
df_new['tags']=df_new['tags'].str.replace('#','')
df_new['tags']=df_new['tags'].str.replace('[none]','', regex = False)

I split the strings in order to obtain for every row a list of tags.

In [18]:
df_new['tags'] = df_new['tags'].str.split('|')
df_new

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Country,like_ratio,cluster_hour
index,,,,,,,,,,,,,,,,,,,
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10 17:00:03+00:00,"[Eminem, Walk, On, Water, Aftermath, Shady, In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...,CA,18.135076,from 17:00 to 17:10
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13 17:00:00+00:00,"[plush, bad unboxing, unboxing, fan mail, idub...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...,CA,75.707346,from 17:00 to 17:10
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12 19:05:24+00:00,"[racist superman, rudy, mancuso, king, bach, r...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,CA,27.3525,from 19:00 to 19:10
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12 18:01:41+00:00,"[ryan, higa, higatv, nigahiga, i dare you, idy...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,CA,66.485168,from 18:00 to 18:10
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09 11:04:14+00:00,"[edsheeran, ed sheeran, acoustic, live, cover,...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...,CA,77.513044,from 11:00 to 11:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375937,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18 13:00:04+00:00,"[aarons animals, aarons, animals, cat, cats, k...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals,US,27.552347,from 13:00 to 13:10
375938,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18 01:00:06+00:00,[],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN,US,157.089005,from 01:00 to 01:10
375939,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18 17:34:22+00:00,[I gave safiya nygaard a perfect hair makeover...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...,US,46.577519,from 17:30 to 17:40
375940,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17 17:00:04+00:00,"[Black Panther, HISHE, Marvel, Infinity War, H...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...,US,67.799368,from 17:00 to 17:10
375941,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17 17:09:38+00:00,"[call of duty, cod, activision, Black Ops 4]",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...,US,1.676616,from 17:00 to 17:10

In [19]:
df_tagged = df_new.explode('tags')

In [20]:
df_tagged = df_tagged[df_tagged['tags'] != '']

In [21]:
df_tagged.groupby('tags')['video_id'].size().sort_values(ascending=False).reset_index(name='number_video')

                                  tags  number_video
0                                funny         15039
1                               comedy         12351
2                                 2018         11912
3                                 news          6488
4                                music          5939
...                                ...           ...
847159   10 DE MARZO 2018 POR INTERNET             1
847160      10 DE MARZO 2018 RESULTADO             1
847161        10 DE MARZO 2018 RESUMEN             1
847162                         + Мирби             1
847163                       (часть 5)             1

[847164 rows x 2 columns]

### 9. Find the tags with the largest number of videos

In [22]:
df_tagged.groupby('tags').size().idxmax()

'funny'

In [23]:
df_tagged.groupby('tags')['video_id'].size().sort_values(ascending=False).head(1)

tags
funny    15039
Name: video_id, dtype: int64

### 10. For each (tag, country) pair, compute average ratio likes/dislikes

In [24]:
df_tagged[df_tagged['like_ratio'].notnull()].groupby(['tags', 'Country'], as_index=False)['like_ratio'].mean()

                                                      tags Country like_ratio
0         ''A por la FORTALEZA'' Capitulo 88 - Segunda ...      MX   2.631019
1               ''Es mucho lo que el país le debe al PRI''      MX   74.02381
2                      'Gandarrappido: The Revenger Squad       CA  20.697017
3                                  (2018) ¿Cual Prefieres?      MX      56.05
4                                   (BLAYA - FAZ GOSTOSO)       FR  25.577882
...                                                    ...     ...        ...
1080908                                                  😥      DE  26.384615
1080909                    😭 résistancelamaindesqueezie ❤️      FR  10.219048
1080910    😭قفز عسكري الوحيد من الطائرة العسكرية الجزائرية      FR   6.223873
1080911                                🚀 smartpixel.com.ua      RU   0.714286
1080912                       🤝 ZARBEX zahlt Schutzgeld!!!      DE  13.989691

[1080913 rows x 3 columns]

### 11. For each (trending_date, country) pair, the video with the largest number of views

In [25]:
df_new['trending_date'] = pd.to_datetime(df_new['trending_date'],
                                         format='%y.%d.%m')

In [26]:
df_new.loc[df_new.groupby(['trending_date', 'Country'])['views'].idxmax()][['video_id', 'trending_date', 'Country', 'views']]

           video_id trending_date Country     views
index
4       2Vv-BfVoq4g    2017-11-14      CA  33523622
40912   2Vv-BfVoq4g    2017-11-14      DE  33523622
81895   2Vv-BfVoq4g    2017-11-14      FR  33523622
122451  2Vv-BfVoq4g    2017-11-14      GB  33523622
161378  ePO5M5DE01I    2017-11-14      IN  35885754
...             ...           ...     ...       ...
219107       #NAME?    2018-06-14      JP   4427381
253755       #NAME?    2018-06-14      KR   4427381
294180  gPHVLxm8U-0    2018-06-14      MX   5829270
334804  i63jWjoAWHE    2018-06-14      RU   6597033
375862  xTlNMmZKwpA    2018-06-14      US  94254507

[1967 rows x 4 columns]

### 12. Divide trending_date into three columns: year, month, day

In [27]:
df_new['year_trend'] = df_new['trending_date'].dt.year
df_new['month_trend'] = df_new['trending_date'].dt.month
df_new['day_trend'] = df_new['trending_date'].dt.day
df_new[['year_trend', 'month_trend', 'day_trend']]

        year_trend  month_trend  day_trend
index
0             2017           11         14
1             2017           11         14
2             2017           11         14
3             2017           11         14
4             2017           11         14
...            ...          ...        ...
375937        2018            6         14
375938        2018            6         14
375939        2018            6         14
375940        2018            6         14
375941        2018            6         14

[373322 rows x 3 columns]

### 13. For each (month, country) pair, the video with the largest number of views

In [28]:
df_new.loc[df_new.groupby(['month_trend', 'Country'])['views'].idxmax()][['video_id', 'month_trend', 'Country', 'views']]

           video_id  month_trend Country      views
index
11214   LsoLEjrDogU            1      CA   43067983
51930   LsoLEjrDogU            1      DE   37728802
92853   LsoLEjrDogU            1      FR   37728802
135208  LsoLEjrDogU            1      GB   90598955
173405  dfnCAmr569k            1      IN   42019590
...             ...          ...     ...        ...
166769  FlsCjmMhFmw           12      IN  125432237
224092  FlsCjmMhFmw           12      KR  113876217
259064  FlsCjmMhFmw           12      MX  100912384
299087  FlsCjmMhFmw           12      RU   52611730
341174  FlsCjmMhFmw           12      US  149376127

[77 rows x 4 columns]

### 14. Read all json files with the video categories

Use the function pd.read_json() to import each file into a Pandas object, and then apply pd.json_normalize() to flatten the nested structure, transforming the list of categories into a tabular DataFrame.

In [29]:
CA_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\CA_category_id.json")
CA_json =pd.json_normalize(CA_json["items"])
DE_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\DE_category_id.json")
DE_json =pd.json_normalize(DE_json["items"])
FR_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\FR_category_id.json")
FR_json =pd.json_normalize(FR_json["items"])
GB_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\GB_category_id.json")
GB_json =pd.json_normalize(GB_json["items"])
IN_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\IN_category_id.json")
IN_json =pd.json_normalize(IN_json["items"])
JP_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\JP_category_id.json")
JP_json =pd.json_normalize(JP_json["items"])
KR_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\KR_category_id.json")
KR_json =pd.json_normalize(KR_json["items"])
MX_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\MX_category_id.json")
MX_json =pd.json_normalize(MX_json["items"])
RU_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\RU_category_id.json")
RU_json =pd.json_normalize(RU_json["items"])
US_json =pd.read_json("C:\\Users\\loren\\OneDrive\\Desktop\\Data Science\\Intro to Computer Science\\trendingYT\\US_category_id.json")
US_json =pd.json_normalize(US_json["items"])

### 15. For each country, determine how many videos have a category that is not assignable.

Work in the same way of first point, by adding Country column and concatenate the dataset.

In [30]:
CA_json['Country'] = 'CA'
DE_json['Country'] = 'DE'
FR_json['Country'] = 'FR'
GB_json['Country'] = 'GB'
IN_json['Country'] = 'IN'
JP_json['Country'] = 'JP'
KR_json['Country'] = 'KR'
MX_json['Country'] = 'MX'
RU_json['Country'] = 'RU'
US_json['Country'] = 'US'

In [31]:
list_country_json = [CA_json, DE_json, FR_json, GB_json, IN_json, JP_json, KR_json, MX_json, RU_json, US_json]
df_json = pd.concat(list_country_json)
df_json

,kind,etag,id,snippet.channelId,snippet.title,snippet.assignable,Country
0,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/Xy1mB4_yLrHy_BmKm...",1,UCBR8-60-B28hp2BmDPdntcQ,Film & Animation,True,CA
1,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/UZ1oLIIz2dxIhO45Z...",2,UCBR8-60-B28hp2BmDPdntcQ,Autos & Vehicles,True,CA
2,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/nqRIq97-xe5XRZTxb...",10,UCBR8-60-B28hp2BmDPdntcQ,Music,True,CA
3,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/HwXKamM1Q20q9BN-o...",15,UCBR8-60-B28hp2BmDPdntcQ,Pets & Animals,True,CA
4,youtube#videoCategory,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/9GQMSRjrZdHeb1OEM...",17,UCBR8-60-B28hp2BmDPdntcQ,Sports,True,CA
...,...,...,...,...,...,...,...
27,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/N1TrDFLRppxZgBowC...",40,UCBR8-60-B28hp2BmDPdntcQ,Sci-Fi/Fantasy,False,US
28,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/7UMGi6zRySqXopr_r...",41,UCBR8-60-B28hp2BmDPdntcQ,Thriller,False,US
29,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/RScXhi324h8usyIet...",42,UCBR8-60-B28hp2BmDPdntcQ,Shorts,False,US
30,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/0n9MJVCDLpA8q7aiG...",43,UCBR8-60-B28hp2BmDPdntcQ,Shows,False,US
31,youtube#videoCategory,"""m2yskBQFythfE4irbTIeOgYYfBU/x5NxSf5fz8hn4loSN...",44,UCBR8-60-B28hp2BmDPdntcQ,Trailers,False,US

In [32]:
df_json[df_json['snippet.assignable'] == False].groupby('Country').size()

Country
CA    17
DE    17
FR    17
GB    17
IN    17
JP    17
KR    17
MX    17
RU    17
US    17
dtype: int64